### ISSUE TITLE
provided g15daemon doesn' start properly

### ISSUE THREAD

**Issue by joe-mojo** [vividnightmare/g510s#13]
From your ppa, installing g15daemon package result in time being displayed on G510 LCD. Seems like only configuration GUI is missing.
Installing g510s package (uninstalling g15daemon package) result in a not working g15daemon service. Systemctl report it as "active(exited)" and g15stats, says it can't connect to g15daemon. Unlike with vanilla g15daemon package, no g15* process name spotted.

**Comment by vividnightmare** [comment]
G510s and g15daemon provide the same functionality.  You can use either of them, or none of them, but not both of them.

If you install G510s, you're no longer using g15daemon.  As a result, you won't be running g15daemon's services.  These are provided internally by G510s.  The process name for G510s is g510s.

G510s supports g15daemon's client screens for compatibility.  As a result, packages that provide such screens will require g15daemon as a dependency (the provided g15stats package is a good example).  So, G510s provides g15daemon so that the package system understands that we have a working implementation of what these screen packages would require, even though we're not using g15daemon.

You can safely ignore g15daemon's availability for eoan.  It's only provided because of Ubuntu's omission of build dependencies and is included in both the current and upcoming LTS releases. #9
