### ISSUE TITLE
g510s process constantly uploading data

### ISSUE THREAD

**Issue by Drek282** [vividnightmare/g510s#27]
I'm wondering why the g510s process is constantly uploading data.  I checked netstat and it shows the g510s process connecting to 0.0.0.0 through port 25.  Am I correct in assuming this has something to do with network diagnostics?  Is this the reason why the keyboard stops functioning when I log out?  Does breaking that connection prevent keyboard function?

**Comment by vividnightmare** [comment]
No, I don't believe it performs network diagnostics.

No, it stops functioning because the process is being run as your user.

Breaking the required connection will at least prevent some features from working, yes.

See the following files for a breakdown of communication.
https://github.com/vividnightmare/g510s/blob/master/g510s-net.c
https://github.com/vividnightmare/g510s/blob/master/g510s-threads.c

Communications for the LCD are handled over a local socket.  If you disconnect your network, you'll see that it continues uninterrupted.

To keep it running when you log out, you could use the older g15daemon software, which runs at a system level.
Be sure to use the version of libg15 here:
https://github.com/vividnightmare/libg15

Or, recompile libg15 and set the read_length value to 8 which prevents G510s from printing duplicate characters erroneously.
```
    // G510/G510s has 8 byte read length
    if(caps & G15_DEVICE_G510) {
        read_length = G13_KEY_READ_LENGTH;
    }
```

**Comment by Drek282** [comment]
Thank you for the response.
